### PR TITLE
Define a generic interface to allow flexibility

### PR DESCRIPTION
**Pull request by danieljbruce**
This PR will allow code that uses this library to be more flexible in terms of the object passed into the function mentioned in index.ts.

### CODE REVIEW

**Comment by murgatroid99** [comment]
This change doesn't match the change described in the latest version of the design doc. Is there a specific reason for that?

**Comment by danieljbruce** [comment]
> This change doesn't match the change described in the latest version of the design doc. Is there a specific reason for that?

I see now. We want what is written in the last heading verbatim.

**Comment by danieljbruce** [comment]
We should not merge this yet. I am getting a `void` response when using this in `nodejs-bigtable` for some reason.

**Comment by danieljbruce** [comment]
I was able to further test this with nodejs-bigtable and I think it looks good to go.

**Review by murgatroid99 — APPROVED** [review]

**Review by ruyadorno — APPROVED** [review]

**Review by Scutua — APPROVED** [review]

**Pull request merged**
